@TestSystem_HostAddress = http://localhost:5155

### Get all tests
GET {{TestSystem_HostAddress}}/api/test
Accept: application/json

### Create a new test
POST {{TestSystem_HostAddress}}/api/test
Content-Type: application/json

{
  "title": "Test di esempio",
  "questions": [
    {
      "text": "Qual è il colore del cielo?",
      "options": [
        { "text": "Blu", "isCorrect": true },
        { "text": "Verde", "isCorrect": false }
      ]
    },
    {
      "text": "Quanto fa 2 + 2?",
      "options": [
        { "text": "3", "isCorrect": false },
        { "text": "4", "isCorrect": true }
      ]
    }
  ]
}
